import Head from "next/head";
import QuoteList from "../components/QuoteList";

export default function Home({ quotes }) {
    return (
        <div>
            <Head>
                <title>Naruto Inspirational Quotes</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css"
                    rel="stylesheet"
                />
            </Head>

            <QuoteList quotes={quotes} />
        </div>
    );
}

export const getStaticProps = async () => {
    const res = await fetch(
        `https://animechan.vercel.app/api/quotes/anime?title=naruto`
    );
    const quotes = await res.json();

    return {
        props: {
            quotes,
        },
    };
};
